# Change these first
owner: kurry-social
repo: ServerStatus
user-agent: "kurrysocial status checkbot"

sites:
  - name: Web
    url: https://kurry.social/about
  - name: API
    url: https://kurry.social/api/v2/instance
  - name: CDN
    url: https://cdn01.kurry.gallery/site_uploads/files/000/000/003/@1x/f0cbefc3a0fb23d4.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.kurry.social
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime for Kurry.social
  introTitle: This site shows the Status of the Kurry.Social
  introMessage: "Upptime is the open-source uptime monitor and status page, powered entirely by GitHub."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
